plugins:
  - babel
env:
  node: true
parser: babel-eslint
extends:
  - 'airbnb-base'
rules:
  no-console: 0
  no-plusplus: 0
  no-underscore-dangle: 0
  no-param-reassign: 0
  quote-props: 0
  max-len: 0
  radix: 0
  indent: [2, 4, {"SwitchCase": 1}]
  it: off
